services:
  wg-easy:
    network_mode: "host"
    environment:
      - WG_HOST=${WG_HOST:?Informe o IP publico do servidor}
      - PASSWORD_HASH=${WG_PASSWORD_HASH:?Informe o hash bcrypt da senha}
      - PORT=51821
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    volumes:
      - ./.wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
